// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbdQamxMGmZ4jYW3ghSO5kgd8NDCvTInU',
    appId: '1:728839891563:android:1b50713812ca4471519f2e',
    messagingSenderId: '728839891563',
    projectId: 'campus-compass-2a4b0',
    databaseURL: 'https://campus-compass-2a4b0-default-rtdb.firebaseio.com',
    storageBucket: 'campus-compass-2a4b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOYt54P_mKxjuzHAld3Xz7dBPQqF53mc',
    appId: '1:728839891563:ios:c445248ab099aad1519f2e',
    messagingSenderId: '728839891563',
    projectId: 'campus-compass-2a4b0',
    databaseURL: 'https://campus-compass-2a4b0-default-rtdb.firebaseio.com',
    storageBucket: 'campus-compass-2a4b0.appspot.com',
    iosBundleId: 'com.example.campusCompass',
  );
}
